//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MC1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public Teacher()
        {
            this.Requests = new HashSet<Request>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string Post { get; set; }
        public string Education { get; set; }
        public Nullable<bool> Available { get; set; }
        public string Location { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public byte[] Picture { get; set; }
    
        public virtual ICollection<Request> Requests { get; set; }
    }
}
